### ISSUE TITLE
You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0

### ISSUE THREAD

**Issue by goldyfruit** [jaredcobb/ovos-skill-openai#1]
This is the error I got when trying to run this skill.
```
Nov 25 10:51:32 rpi3b ovos-core[1248]: 2023-11-25 10:51:32.576 - skills - ovos_workshop.skills.fallback:_handle_fallback_request:384 - ERROR - Exception in fallback.
Nov 25 10:51:32 rpi3b ovos-core[1248]: Traceback (most recent call last):
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_skill_openai/__init__.py", line 119, in open_ai_get_response
Nov 25 10:51:32 rpi3b ovos-core[1248]:     response = openai.ChatCompletion.create(**payload)
Nov 25 10:51:32 rpi3b ovos-core[1248]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/openai/_utils/_proxy.py", line 22, in __getattr__
Nov 25 10:51:32 rpi3b ovos-core[1248]:     return getattr(self.__get_proxied__(), attr)
Nov 25 10:51:32 rpi3b ovos-core[1248]:                    ^^^^^^^^^^^^^^^^^^^^^^
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
Nov 25 10:51:32 rpi3b ovos-core[1248]:     return self.__load__()
Nov 25 10:51:32 rpi3b ovos-core[1248]:            ^^^^^^^^^^^^^^^
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/openai/lib/_old_api.py", line 33, in __load__
Nov 25 10:51:32 rpi3b ovos-core[1248]:     raise APIRemovedInV1(symbol=self._symbol)
Nov 25 10:51:32 rpi3b ovos-core[1248]: openai.lib._old_api.APIRemovedInV1:
Nov 25 10:51:32 rpi3b ovos-core[1248]: You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
Nov 25 10:51:32 rpi3b ovos-core[1248]: You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
Nov 25 10:51:32 rpi3b ovos-core[1248]: Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
Nov 25 10:51:32 rpi3b ovos-core[1248]: A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
Nov 25 10:51:32 rpi3b ovos-core[1248]: During handling of the above exception, another exception occurred:
Nov 25 10:51:32 rpi3b ovos-core[1248]: Traceback (most recent call last):
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_workshop/skills/fallback.py", line 378, in _handle_fallback_request
Nov 25 10:51:32 rpi3b ovos-core[1248]:     if handler(message):
Nov 25 10:51:32 rpi3b ovos-core[1248]:        ^^^^^^^^^^^^^^^^
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_skill_openai/__init__.py", line 66, in handle_fallback_response
Nov 25 10:51:32 rpi3b ovos-core[1248]:     response = self.open_ai_get_response(utterance)
Nov 25 10:51:32 rpi3b ovos-core[1248]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 10:51:32 rpi3b ovos-core[1248]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_skill_openai/__init__.py", line 121, in open_ai_get_response
Nov 25 10:51:32 rpi3b ovos-core[1248]:     except openai.error.OpenAIError as e:
Nov 25 10:51:32 rpi3b ovos-core[1248]:            ^^^^^^^^^^^^
Nov 25 10:51:32 rpi3b ovos-core[1248]: AttributeError: module 'openai' has no attribute 'error'
```

**Comment by goldyfruit** [comment]
Seems `openai` must be pinned to `0.28`
